/**
 * @file src/types/profile.ts
 * @description Core TypeScript interfaces for the NFC Digital Business Card platform.
 *
 * These types map 1-to-1 with the `profiles` table columns in Supabase.
 * JSONB columns are represented as typed interfaces for full type-safety.
 */

// ─── Primitive sub-types (stored in JSONB columns) ───────────────────────────

/**
 * Flexible contact information block stored in the `contact_info` JSONB column.
 */
export interface ContactInfo {
  email?: string;
  phone?: string;
  address?: string;
  /** Full Google Maps URL or embed URL */
  maps_url?: string;
  website?: string;
  // ── Professional identity (stored in JSONB — no schema migration needed) ──
  /** Job title / role */
  job_title?: string;
  /** Company or brand name */
  company?: string;
  // ── Visual / brand metadata ───────────────────────────────────────────────
  /** Primary brand hex colour, e.g. "#4a1c1c" */
  brand_color?: string;
  /** Public URL of the cover / hero photo */
  cover_url?: string;
  /** Public URL of the company logo */
  logo_url?: string;
}

/**
 * A single social platform entry stored inside the `social_links` JSONB array.
 */
export interface SocialLink {
  /** e.g. "LinkedIn", "Facebook", "Telegram", "Instagram" */
  platform: string;
  url: string;
  /** Optional icon identifier (e.g. "linkedin", "facebook") for icon-rendering */
  icon?: string;
}

/**
 * A single custom link entry stored inside the `custom_links` JSONB array.
 * Used for any non-social link (e.g. "Our Menu", "Book a Table", "Case Studies").
 */
export interface CustomLink {
  title: string;
  url: string;
  /** Optional description shown below the link title */
  description?: string;
}

// ─── Profile types ────────────────────────────────────────────────────────────

/**
 * Discriminated union for the `profile_type` column.
 * Extend this union as you add more entity types to the platform.
 */
export type ProfileType = "individual" | "business" | "restaurant" | "hotel" | "legal";

// ─── Main Profile interface ───────────────────────────────────────────────────

/**
 * Full profile record as it exists in the Supabase `profiles` table.
 */
export interface Profile {
  /** UUID primary key (auto-generated by Supabase) */
  id: string;
  /** URL-safe unique identifier, e.g. "hotel-skylight" → /p/hotel-skylight */
  slug: string;
  /** Entity type – drives UI rendering decisions */
  profile_type: ProfileType;
  /** Display name of the person or business */
  name: string;
  /** Short bio / tagline / description */
  bio: string | null;
  /** Public URL to avatar, logo, or profile picture */
  avatar_url: string | null;
  /** Flexible contact details (JSONB) */
  contact_info: ContactInfo | null;
  /** Array of social platform links (JSONB) */
  social_links: SocialLink[] | null;
  /** Array of custom/extra links (JSONB) */
  custom_links: CustomLink[] | null;
  /** ISO 8601 timestamp – set automatically by Supabase */
  created_at: string;
}

// ─── Input / Form types ───────────────────────────────────────────────────────

/**
 * Data shape accepted by the `createProfile` server action.
 * Omits server-managed fields (`id`, `created_at`).
 * `slug` is optional – one is auto-generated when absent.
 */
export type CreateProfileInput = Omit<Profile, "id" | "created_at"> & {
  slug?: string;
};

/**
 * Data shape accepted by the `updateProfile` server action.
 * All fields are optional except `id`.
 */
export type UpdateProfileInput = Partial<Omit<Profile, "id" | "created_at">> & {
  id: string;
};
